// axonius/src/components/Dashboard.vue
<script setup>
import Card from './Card.vue'
</script>

<template>
  <div class="axonius-dashboard">
    <h1>Welcome to the Axonius Dashboard</h1>
    <h2>Made with Vue + Vite</h2>
    <div class="axonius-card-panel">
        <Card/>
        <Card/>
    </div>
  </div>
</template>

<style>
.axonius-dashboard {
  display: flex;
  flex-direction: column;
  text-align: center;
  color:  #dc3545;
}

.axonius-card-panel {
  display: flex;
  flex-direction: row;
  justify-content: space-around;
  margin-top: 50px;
}
</style>

// home/src/Dashboard.jsx
import Button from "./Button";
import React from "react";
import './App.scss';
import Card from './Card';

const Dashboard = () => (
    <div class="axoniusx-dashboard">
        <h1>Welcome to the AxoniusX Dashboard</h1>
        <h2>Made with React + Vite</h2>
        <div class="axoniusx-card-panel">
            <Card/>
            <Card/>
        </div>
     </div>
);

export default Dashboard;
